"""Change screenshot to string

Revision ID: 8d633d2089d7
Revises: 
Create Date: 2024-09-18 03:35:40.867143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d633d2089d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.alter_column('screenshot',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.alter_column('screenshot',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
